name: Generate Rules
on: push

jobs:
  generate:
    name: Generate rules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno run --allow-write=_site rulegen/main.ts
      - uses: actions/upload-pages-artifact@v1

  deploy:
    name: Deploy rules
    runs-on: ubuntu-latest
    needs: [generate]

    permissions:
      pages: write
      id-token: write

    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v2
